### ISSUE TITLE
unable to use UDF

### ISSUE THREAD

**Issue by howking** [GoogleCloudPlatform/bigquery-geo-viz#3]
Thanks for great tool ! but I have been unable to use UDF in the past few days.
```
Syntax error: Unexpected keyword CREATE at [5:1]
```

**Comment by donmccurdy** [comment]
Thanks, would you be able to share an example of a query that's broken?

**Comment by donmccurdy** [comment]
The issue is related to converting geography columns to GeoJSON automatically, which requires this visualization tool to wrap the query for the conversion. That wrapping fails with UDF.

Note that [support for persistent UDF is in progress](https://issuetracker.google.com/35905921), which would provide a workaround once it's available.

**Comment by mentin** [comment]
Note that persistent UDF access is now public, so the workaround for this issue is 
1. run `CREATE FUNCTION dataset.function_name ..` in a separate statement in regular BigQuery UI, then 
2. call this function in GeoViz query.

This avoids CREATE FUNCTION statements in GeoViz query. It also allows reusing UDFs without defining them in every query.
